sdlc scripts

diff --git a/src/main/resources/archetype-resources/.sdlc/deploy-release b/src/main/resources/archetype-resources/.sdlc/deploy-release
--- a/src/main/resources/archetype-resources/.sdlc/deploy-release
+++ b/src/main/resources/archetype-resources/.sdlc/deploy-release
@@ -14,16 +14,15 @@ hash mvn 2>/dev/null || {
   exit 1
 }
 
-mvn_settings_path="${prj_home}/.mvn/settings.xml"
-[[ -e "$mvn_settings_path" ]] || {
-  echo "Maven settings file '${mvn_settings_path}' not found: aborting"
-  exit 1
-}
-
 # Comma-delimited list of profiles to activate
 mvn_profiles='release'
 
-mvn --no-transfer-progress --batch-mode --activate-profiles "$mvn_profiles" -s "$mvn_settings_path" install deploy \
-    -Dhttps.protocols=TLSv1.2 \
-    "-DaltDeploymentRepository=nexus.atoito::http://nexus.atoitogroup.it:8081/repository/maven-snapshots" \
-    "-DaltReleaseDeploymentRepository=nexus.atoito::http://nexus.atoitogroup.it:8081/repository/maven-releases"
+mvn_settings_path="${prj_home}/.mvn/settings.xml"
+[[ -e "$mvn_settings_path" ]] || {
+  echo "Maven settings file '${mvn_settings_path}' not found: local install"
+  mvn --no-transfer-progress --batch-mode --activate-profiles "$mvn_profiles" install
+  exit 1
+}
+
+echo "Deploy using Maven settings '${mvn_settings_path}'"
+mvn --no-transfer-progress --batch-mode --activate-profiles "$mvn_profiles" -s "$mvn_settings_path" install deploy
